sspx.web/Models/ImportComments.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace sspx.web.Models
{
    public class ImportComments
    {
        public int ProtocolVersionsKey { get; set; }
        public string Version { get; set; }
        public List<Reviewer> Reviewers { get; set; }
        public int Comments { get; set; }
    }

    public class Reviewer {
        public string ReviewerName { get; set; }
        public int? ReviewerID { get; set; }
        public int ReviewerComments { get; set; }
    }

}

sspx.web/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using sspx.core;
using sspx.core.entities;
using sspx.core.interfaces;

namespace sspx.web.Controllers
{
    public class AdminController : Controller
    {
        private readonly IRepository<Protocol> _protocolRepository;

        public AdminController(IRepository<Protocol> protocolRepository)
        {
            _protocolRepository = protocolRepository;
        }

        public IActionResult Index()
        {
            var items = _protocolRepository.List();
            return View(items);
        }

        public IActionResult Edit()
        {
            var items = _protocolRepository.List();
            return View(items);
        }
    }
}

sspx.web/Controllers/ProtocolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using sspx.core;
using sspx.core.entities;
using sspx.core.interfaces;

namespace sspx.web.Controllers
{
    public class ProtocolController : Controller
    {
        private readonly IRepository<Protocol> _protocolRepository;

        public ProtocolController(IRepository<Protocol> protocolRepository)
        {
            _protocolRepository = protocolRepository;
        }

        public IActionResult Index()
        {
            var protocols = _protocolRepository.List();
            return View(protocols);
        }

        public IActionResult Load()
        {
            int recordsAdded = DatabasePopulator.LoadProtocols(_protocolRepository);
            return Ok(recordsAdded);
        }

        public IActionResult Edit()
        {
            var protocols = _protocolRepository.List();
            return View(protocols);
        }
    }
}

sspx.web/ViewComponents/NavMenuViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using sspx.web.Models;
using sspx.web.Helpers;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Linq;
using sspx.web.Services;

namespace sspx.web.ViewComponents
{
    public class NavMenuViewComponent : ViewComponent
    {
        private SignInManager<IdentitySSPxUser> _signInManager;
        private INavMenuData _navMenuData;
        private IAdminPermissions _adminPermissions;

        public NavMenuViewComponent(SignInManager<IdentitySSPxUser> signInManager, INavMenuData navMenuData, IAdminPermissions adminPermissions)
        {
            _signInManager = signInManager;
            _navMenuData = navMenuData;
            _adminPermissions = adminPermissions;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            NavMenuModel model = new NavMenuModel();

            model.SignedIn = _signInManager.IsSignedIn(this.UserClaimsPrincipal);
            if(model.SignedIn == false)
            {
                return View(model);
            }

            model.UserKey = HttpContext.Session.Get<int>("userKey");
            model.AdminMenuPermission = _adminPermissions.GetForUser(model.UserKey);
            model.UserFullName = HttpContext.Session.Get<string>("userFullName");
            
            model.FirstMenuSelection = "Menu";
            model.SecondMenuSelection = "Select";

            string path = Request.Path.ToString().ToLower();

            // TODO CS2:
            model.PathTest = path;

            string razorPagePath = RouteData.Values.ContainsKey("page") ? RouteData.Values["page"].ToString().ToLower() : string.Empty;
            string idFromRoute = string.Empty;
            if (RouteData.Values.ContainsKey("pid"))
            {
                idFromRoute = RouteData.Values["pid"].ToString();
            }
            else if (RouteData.Values.ContainsKey("vid"))
            {
                idFromRoute = RouteData.Values["vid"].ToString();
            }

            if (path.StartsWith("/dashboard/") || path == "/")
            {
                model.FirstMenuSelection = "Dashboard";
            }
            else if (path.StartsWith("/admin"))
            {
                model.FirstMenuSelection = "Admin";
                model.SecondMenuSelection = AdminNavMenuItem.FromPagePath(razorPagePath).DisplayText;
            }
            else if (path.StartsWith("/protocols") || path.StartsWith("/workflow"))
            {
                model.FirstMenuSelection = "Protocols";

                model.ProtocolGroupMenuItems = await _navMenuData.GetProtocolGroupMenuItems();

                List<ProtocolMenuItem> protocolMenuItems = await _navMenuData.GetProtocolMenuItems(model.UserKey);
                model.ProtocolMenuItems = protocolMenuItems;

                if (idFromRoute != string.Empty)
                {
                    model.SelectedProtocolKey = int.Parse(idFromRoute);
                    var currentProtocol = protocolMenuItems.Where(m => m.Id == model.SelectedProtocolKey).FirstOrDefault();
                    if(currentProtocol != null)
                    {
                        model.SecondMenuSelection = currentProtocol.Name;
                    }

                    // TODO CS2:
                    List<ProtocolVersionMenuItem> protocolVersionMenuItems = await _navMenuData.GetProtocolVersions(model.SelectedProtocolKey);
                    model.ProtocolVersionMenuItems = protocolVersionMenuItems;

                    if (protocolVersionMenuItems.Any())
                    {
                        var currentProtocolVersionMenuItem = protocolVersionMenuItems.FirstOrDefault();
                        model.ProtocolVersionSelection = "Work Version";
                        model.ProtocolVersionLastUpdated = $"Last updated: {currentProtocolVersionMenuItem.LastUpdatedDate.ToShortDateString()}";
                    }
                    else
                    {
                        model.ProtocolVersionSelection = "No Versions available";
                        model.ProtocolVersionLastUpdated = string.Empty;
                    }
                }
            }

            return View(model);
        }
    }
}

sspx.web/Views/Shared/_Comments.cshtml
@model sspx.web.Models.ChecklistNoteViewModel
<style>
    #DeleteMetaData .comment-sample {
        overflow: auto;
        height: 100px;
        width: 95%;
        border: 1px solid #cccccc;
        padding: 3px 5px;
    }

    #commentSection {
        padding: 5px;
    }

    /*table {
        width: 100%;
        margin: 20px 0;
        border-collapse: collapse;
    }

    table, th, td {
        border: 1px solid #cdcdcd;
    }

       table th, table td {
            padding: 5px;
            text-align: left;
      }*/

</style>
<div id="EditMetaData" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <textarea id="metaEditor" style="height:300px; width:100%; clear:both" spellcheck="false"></textarea>
            </div>
            <div class="modal-footer">
                <button id="EditButton" type="button" class="btn btn-success" onclick="saveComment($(this));" disabled="disabled">Save</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<div id="ImportMetaData" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Import Comments</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="bodyImportProtocol">

                </div>
                @*<div class="modal-footer">
                    <button id="EditButton" type="button" class="btn btn-success" disabled="disabl  ed">Import</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>*@
            </div>
        </div>
    </div>
<div id="DeleteMetaData" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Remove Comment</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to remove this comment?</p>
                <div class="comment-sample"></div>
            </div>
            <div class="modal-footer">
                <button id="RemoveComment" type="button" class="btn btn-primary" onclick="removeComment($(this));">Remove</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<div id="Comment" class="panel" style="display:block;">
    <div class="addMeta" data-toggle="modal" data-target="#EditMetaData" data-type="C" data-id="0"><i class="fas fa-plus"></i> ADD COMMENT</div>
    @*<div class="addMeta" id="buttonImportMetaData" data-toggle="modal" data-target="#ImportMetaData" data-type="C" data-id="0"> IMPORT COMMENT</div>*@
    <div id="commentSection" class="innerPanel"></div>
</div>

<script src="~/js/sspx/commentObject.js?v=20190201"></script>
<script>
    var comments = @Html.Raw(Json.Serialize(Model.comments));
    var commentProtocolCKey = '@Model.protocolCkey';
    var commentProtocolVersionKey = '@Model.protocolVersionKey';

    function saveComment(button) {
        var cid = button.attr('data-id');
        var metadata = $("#metaEditor").data("kendoEditor").value();
        commentObject.saveComment(cid, metadata);
        return false;
    }

    function removeComment(button) {
        var cid = button.attr('data-id');
        commentObject.removeComment(cid);
        return false;
    }

    $('#EditMetaData').on('show.bs.modal', function (event) {
        var object = $(event.relatedTarget);
        var id = object.data('id');
        var modal = $(this);
        var title = (id == '0') ? 'Add Comment' : 'Edit Comment';
        modal.find('.modal-title').text(title);
        if (id != '0') {
            var data = commentObject.getCommentById(id);
            $("#metaEditor").data("kendoEditor").value(data[0].comment);
        } else {
            $("#metaEditor").data("kendoEditor").value('');
        }
        modal.find('#EditButton').attr('data-id', id).attr('disabled', 'disabled');
    });

    $('#DeleteMetaData').on('show.bs.modal', function (event) {
        var object = $(event.relatedTarget);
        var id = object.data('id');
        var modal = $(this);
        var data = commentObject.getCommentById(id);
        modal.find('.comment-sample').html(data[0].comment);
        modal.find('#RemoveComment').attr('data-id', id);
    });

    function setMetaSaveActive() {
        $('#EditMetaData #EditButton').removeAttr('disabled');
    }

    $(document).ready(function () {
        commentObject.init(comments, commentProtocolVersionKey);
        commentObject.populateComment();
        $("#metaEditor").kendoEditor({
            pasteCleanup: {
                all: false,
                css: false,
                keepNewLines: false,
                msAllFormatting: false,
                msConvertLists: false,
                msTags: false,
                none: true,
                span: false
            },
            resizable: {
                content: false,
                toolbar: false
            },
            execute: setMetaSaveActive,
            keyup: setMetaSaveActive
        }).getKendoEditor();
    });

    $("#buttonImportMetaData").click(function () {
        @*$.get('@Url.Action("ImportCommentVersions", "Home")', {}, function (response) {
            $("#bodyImportProtocol").html(response);*@

        $.ajax({
            type: "GET",
            url: "../SSPxImportComment/ImportComments/"+commentProtocolCKey + "/" + commentProtocolVersionKey,
            contentType: "application/json; charset=utf-8",
            data: { 'ProtocolsKey': commentProtocolCKey, 'WorkingProtocolVersionKey': commentProtocolVersionKey },
            dataType: "html",
            success: function (result, status, xhr) {

                //var markup = "<tr><td><input type='checkbox' name='record'></td><td>" + 'name' + "</td><td>" + 'email' + "</td></tr>";
                //$("table tbody").append(markup);

                $("#bodyImportProtocol").html(result);
            },
            error: function (xhr, status, error) {
                $("#bodyImportProtocol").html("Result: " + status + " " + error + " " + xhr.status + " " + xhr.statusText)
            }
        });
    });

</script>

sspx.web/Views/Shared/_Layout.cshtml
<!-- !DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - sspx.web</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">sspx.web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - ONTOADAPTIVE, LLC</p>
        </!footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.2.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Prototype</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    @RenderSection("topStyles", required: false)
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    @RenderSection("topScripts", required: false)
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">SSPx</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                    <li class="active"><a asp-area="" asp-controller="Home" asp-action="Spike">***spike</a></li>
                    <li><a asp-area="" asp-controller="Protocol" asp-action="Edit">Protocol</a></li>
                    <!-- NAA. Add more use cases here.  -->
                    <li><a asp-page="/Dashboard/View">Dashboard</a></li>
                    <li><a asp-page="/Status/View">Status Updates</a></li>
                    <li><a asp-area="" asp-controller="Admin" asp-action="Edit">Admin</a></li>
                    <li><a asp-page="/Help/View">Help</a></li>
                </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            @RenderBody()
            <div class="col-xs-12 col-sm-4 col-md-2 col-lg-2">
                @RenderSection("leftSection", required: false)
            </div>
            <div class="col-xs-12 col-sm-8 col-md-7 col-lg-7">
                @RenderSection("midSection", required: false)
            </div>
            <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                @RenderSection("rightSection", required: false)
            </div>
        </div>
        <div style="clear:both;padding:20px"></div>
        @RenderSection("bottomScripts", required: false)
    </body>
    </html>

sspx.web/Views/Shared/_ProtocolLayout.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<!DOCTYPE html>
<html lang="en">
<head>
    <title>SSPx Prototype</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <partial name="_StylesScriptsPartial" />
    <partial name="_KendoStylesScripts" />
    <link rel="stylesheet" href="~/css/sspx/sspxprotocol.css?v=20190201">
    <style>
        .k-editor-toolbar .k-button-group .k-tool {
            width: 28px !important;
            height: 28px !important;
            line-height: 28px !important;
        }
    </style>
    @RenderSection("topScripts", required: false)
    <partial name="_StyleOverridesLinkLast" />
</head>
<body>
    @await Component.InvokeAsync("NavMenu")
    @*
        TODO: if we want cookie consent popup, uncomment and get this to show up correctly (right now it's a weird small button)
        <partial name="_CookieConsentPartial" />
    *@
    <div class="container-fluid protocolEditorText">
        <div id="topSection" class="row" style="width:100%">
            @RenderSection("topSection", required: false)
        </div>
        <div class="row">
            <div id="col1" class="col-xs-12 col-sm-5 col-md-3 col-lg-3" style="padding-right: 0px">
                @RenderSection("leftSection", required: false)
            </div>
            <div id="col2" class="col-xs-12 col-sm-7 col-md-5 col-lg-5" style="padding: 0px">
                @RenderSection("midSection", required: false)
            </div>
            <div id="col3" class="col-xs-12 col-sm-12 col-md-4 col-lg-4" style="padding-left: 0px">
                @RenderSection("rightSection", required: false)
            </div>
        </div>
    </div>
    <partial name="_FooterPartial" />
    @RenderSection("bottomContent", required: false)
    <script>
        var appHeight = 0;
        $('document').ready(function () {
            resizeContainer();
        });
        $(window).resize(function () {
            resizeContainer();
        });
        function resizeContainer() {
            var windowHeight = window.innerHeight;
            appHeight = windowHeight;
            if (windowHeight) {
                var maxHeight = windowHeight - 125;
                appHeight = maxHeight;
                if (maxHeight > 600) {
                    var height = maxHeight + 'px';
                    var col1Height = (maxHeight - 30) + 'px';
                    $('#protocolNodes').css('height', col1Height);
                    $('#protocolNotes').css('height', height);
                    $('.contentArea').css('height', height);
                    $('.panel').css('height', (maxHeight - 2) + 'px');
                    $('.panelSection').css('height', height);
                }
            }
        }
    </script>
</body>
</html>

sspx.web/Views/Shared/_ProtocolLayout_responsive.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<!DOCTYPE html>
<html lang="en">
<head>
    <title>SSPx Prototype</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <partial name="_StylesScriptsPartial" />
    <partial name="_KendoStylesScripts" />
    <link rel="stylesheet" href="~/css/sspx/sspxprotocol_responsive.css?v=20190108">
    <style>
        .k-editor-toolbar .k-button-group .k-tool {
            width: 28px !important;
            height: 28px !important;
            line-height: 28px !important;
        }
    </style>
    @RenderSection("topScripts", required: false)
    <partial name="_StyleOverridesLinkLast" />
</head>
<body>
    @await Component.InvokeAsync("NavMenu")
    @*
        TODO: if we want cookie consent popup, uncomment and get this to show up correctly (right now it's a weird small button)
        <partial name="_CookieConsentPartial" />
    *@
    <div class="container-fluid protocolEditorText">
        <div id="topSection" class="row" style="width:100%">
            @RenderSection("topSection", required: false)
        </div>
        <div class="row">
            <div id="col1" class="col-xs-12 col-sm-5 col-md-3 col-lg-3" style="padding-right: 0px">
                @RenderSection("leftSection", required: false)
            </div>
            <div id="col2" class="col-xs-12 col-sm-7 col-md-5 col-lg-5" style="padding: 0px">
                @RenderSection("midSection", required: false)
            </div>
            <div id="col3" class="col-xs-12 col-sm-12 col-md-4 col-lg-4" style="padding-left: 0px">
                @RenderSection("rightSection", required: false)
            </div>
        </div>
    </div>
    <partial name="_FooterPartial" />
    @RenderSection("bottomContent", required: false)
    <script>
        var appHeight = 0;
        $('document').ready(function () {
            resizeContainer();
        });
        $(window).resize(function () {
            resizeContainer();
        });
        function resizeContainer() {
            var windowHeight = window.innerHeight;
            appHeight = windowHeight;
            if (windowHeight) {
                var maxHeight = windowHeight - 125;
                appHeight = maxHeight;
                if (maxHeight > 600) {
                    var height = maxHeight + 'px';
                    var col1Height = (maxHeight - 30) + 'px';
                    $('#protocolNodes').css('height', col1Height);
                    $('#protocolNotes').css('height', col1Height);
                    $('.contentArea').css('height', height);
                    $('.panel').css('height', (maxHeight - 2) + 'px');
                    $('.panelSection').css('height', height);
                }
            }
        }
    </script>
</body>
</html>

sspx.web/Views/Shared/_UserAssignment.cshtml
@model sspx.web.Models.UserAssignmentModel
@using sspx.web.Services
@using Microsoft.Extensions.Options
@inject IOptionsMonitor<PreviewOptions> PreviewOptionsAccessor
@{
    var controlId = "ua_" + Model.role;
}
<div class="userAssignmentContainer" id="@controlId">
    <div class="searchContainer">
        <div class="title">@Model.title  <i class="fas fa-search"></i></div>
        <div class="searchResult" style="display:none">
            <input class="searchName" type="text" placeholder="Enter Name" />
            <div class="searchUser"></div>
        </div>
    </div>
    <div class="userContainer"></div>
</div>
<script>
    var objUA_@Model.role = null;
    function UserAssignmentControl (role, controlId) {
        this.role = role;
        this.controlId = controlId;
        this.jqObject = $('#' + controlId);
        this.stopSearch = false;
    }
    UserAssignmentControl.prototype.initUser = function (user) {
        this.jqObject.find('.userContainer').html('');
        for (var i = 0; i < user.length; i++) {
            if (user[i].role === this.role) {
                var html = "<div class='user' data-id='" + user[i].userId + "'>" + user[i].userName + getUserSymbol(this.role) + "<i class='fas fa-trash-alt'></i></div>";
                this.jqObject.find('.userContainer').append(html);
                }
        }
    };
    UserAssignmentControl.prototype.toggleSearch = function () {
        this.jqObject.find('.searchResult').toggle();
        this.jqObject.find('.searchResult .searchName').val('');
        this.jqObject.find('.searchResult .searchUser').html('');
        this.jqObject.find('.searchResult .searchName').focus();

        if (this.jqObject.find('.searchResult:visible').length > 0) {
            this.searchUser( this.jqObject.find('.searchResult .searchName') );
        }
    };
    UserAssignmentControl.prototype.removeUser = function (drop) {
        var user = drop.parent('.user')
        var userId = user.attr('data-id');
        user.remove();
        var oIndex = findindex(allUsers, 'userId', userId);
        allUsers[oIndex].role = '';
        setSaveActive();
    };
    UserAssignmentControl.prototype.searchUser = function (searchbox) {
        this.stopSearch = true;
        var text = searchbox.val();
        this.jqObject.find('.searchResult .searchUser').html('');
        text = text.toLowerCase();
        this.stopSearch = false;
        for (var i = 0; i < allUsers.length; i++) {
            if (allUsers[i].role == '' && allUsers[i].searchText.indexOf(text) >= 0 && !this.stopSearch) {
                var html = "<div class='user' data-id='" + allUsers[i].userId + "'>" + allUsers[i].userName + "</div>";
                this.jqObject.find('.searchResult .searchUser').append(html);
            }
        }
    };
    UserAssignmentControl.prototype.addUser = function (user) {
        var userId = user.attr('data-id');
        var oIndex = findindex(allUsers, 'userId', userId);
        this.toggleSearch();
        var html = "<div class='user' data-id='" + allUsers[oIndex].userId + "'>" + allUsers[oIndex].userName + getUserSymbol(this.role) + "<i class='fas fa-trash-alt'></i></div>";
        this.jqObject.find('.userContainer').append(html);
        allUsers[oIndex].role = this.role;
        setSaveActive();
    };
    function getUserSymbol(role) {
        return role.toLowerCase() == "author" ? "@PreviewOptionsAccessor.CurrentValue.SSPX_AUTHORS_PRIMARY_SYMBOL" : "";
    }
    $(document).ready(function () {
        objUA_@Model.role = new UserAssignmentControl('@Model.role', '@controlId');
        $('#' + '@controlId').on('click', '.fa-search', function () { (objUA_@Model.role).toggleSearch(); });
        $('#' + '@controlId').on('click', '.fa-trash-alt', function () { (objUA_@Model.role).removeUser($(this)); });
        $('#' + '@controlId').on('keyup', '.searchResult .searchName', function () { (objUA_@Model.role).searchUser($(this)); });
        $('#' + '@controlId').on('click', '.searchResult .searchUser .user', function () { (objUA_@Model.role).addUser($(this)); });
    });
</script>