sspx.web/Controllers/HomeController.cs
using System;
using System.Text;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;
using Newtonsoft.Json;
using sspx.infra.config;
using sspx.infra.data;
using sspx.core.entities;
using sspx.core.interfaces;
using sspx.web.Models;
using sspx.web.Helpers;
using sspx.web.Services;
using Microsoft.AspNetCore.Authorization;
using System.Linq;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Wordprocessing;
using System.IO;

namespace sspx.web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ISSPxConfig _config;
        private readonly IProtocolPermissions _protocolPermissions;
        private readonly IHostingEnvironment _hostingEnvironment;
        List<ChecklistItem> results = new List<ChecklistItem>();
        //int firstTime = 0;
        List<ExplanatoryNote> notes = new List<ExplanatoryNote>();
        private String _userKey;
        private String _fullName;

        public HomeController(ISSPxConfig config, IProtocolPermissions protocolPermissions, IHostingEnvironment hostingEnvironment)
        {
            _config = config;
            _protocolPermissions = protocolPermissions;
            _hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Error()
        {
            return View();
        }

        #region Output

        public IActionResult SSPxBuildPdf(String pid)
        {
            return View("SSPxBuildPdf", pid);
        }

        public IActionResult SSPxBuildMSWord(String pid)
        {
            return View("SSPxBuildMSWord", pid);
        }
        /// <summary>
        /// Create PDF File to download
        /// </summary>
        /// <param name="contentType"></param>
        /// <param name="base64"></param>
        /// <returns></returns>
        // based on https://docs.telerik.com/kendo-ui/framework/save-files/introduction
        [HttpPost]
        public IActionResult SSPxOutputPdf(String contentType, String base64)
        {
            var fileContents = Convert.FromBase64String(base64);
            var response = new FileContentResult(fileContents, "application/octet-stream");
            response.FileDownloadName = "Protocol.pdf";
            return response;
        }

        public IActionResult SSPxOutputWord1(String contentType, String base64)
        {
            var fileContents = Encoding.ASCII.GetBytes(contentType);
            return File(fileContents, "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "Protocoldoc.docx");
        }
        /// <summary>
        /// Create MS Word File to download
        /// </summary>
        /// <param name="contentType"></param>
        /// <param name="base64"></param>
        /// <returns></returns>
        public IActionResult SSPxOutputWord(String contentType, String base64)
        {
            MemoryStream ms;
            MainDocumentPart mainPart;
            Body body;
            Document doc;
            AlternativeFormatImportPart chunk;
            AltChunk altChunk;
            string webRootPath = _hostingEnvironment.WebRootPath;
            string contentRootPath = _hostingEnvironment.ContentRootPath;
            string basedirectory = AppContext.BaseDirectory;
            string documentname = "\\Protocolword" + ".docx";

            string altChunkID = "AltChunkId";
            ms = new MemoryStream();
            using (WordprocessingDocument myDoc = WordprocessingDocument.Create(webRootPath + "\\Protocolword.docx", WordprocessingDocumentType.Document))
            {
                mainPart = myDoc.MainDocumentPart;
                if (mainPart == null)
                {
                    mainPart = myDoc.AddMainDocumentPart();
                    body = new Body();
                    doc = new Document(body);
                    doc.Save(mainPart);
                }
                chunk = mainPart.AddAlternativeFormatImportPart(AlternativeFormatImportPartType.Xhtml, altChunkID);
                using (Stream chunkStream = chunk.GetStream(FileMode.Create, FileAccess.Write))
                {
                    using (StreamWriter stringStream = new StreamWriter(chunkStream))
                    {
                        stringStream.Write(contentType);
                    }
                }
                altChunk = new AltChunk();
                altChunk.Id = altChunkID;
                mainPart.Document.Body.InsertAt(altChunk, 0);
                mainPart.Document.Save();
            }
            return PhysicalFile(webRootPath + "\\Protocolword.docx", "application/ms-word", "Protocolword.docx");

        }

        public IActionResult SSPxDownloadPdf(String contentType, String base64)
        {
            byte[] fileBytes = System.IO.File.ReadAllBytes(base64);
            var response = new FileContentResult(fileBytes, "application/octet-stream");
            response.FileDownloadName = "Protocol.pdf";
            return response;
        }


        #endregion

        #region Protocol Detail

        [Authorize]
        public IActionResult SSPxProtocol(String pid = "7")
        {
            int commentCount = 0;
            // using local DBHelper calls
            GetUserData();

            bool hasEditPermission = _protocolPermissions.HasPermission(Convert.ToInt32(_userKey), Convert.ToInt32(pid), ProtocolPermissionTypes.EditProtocol);
            if (hasEditPermission == false)
            {
                return RedirectToPage("/Index", new { area = "Dashboard" });
            }
            Int32 protocolVersionKey = DBHelper.GetProtocolVersion(_config.SSPxConnectionString, pid);
            var resultSet = DBHelper.GetProtocolVersionCommentsForAll(_config.SSPxConnectionString, protocolVersionKey.ToString());
            // commentsCalculation(resultSet);
            //SSP 136 - Get totoal number of count for a protocol
            for (int i = 0; i < resultSet.Count; i++)
            {
                if (resultSet[i].roleKey == Convert.ToInt32(RoleTypes.Author))
                    commentCount += 1;
                else if (resultSet[i].roleKey == Convert.ToInt32(RoleTypes.Reviewer))
                    commentCount += 1;
            }

            //SSP 136 - Get totoal number of count for a protocol
            ChecklistNoteViewModel protocol = new ChecklistNoteViewModel
            {
                protocolCkey = pid,
                comments = DBHelper.GetProtocolVersionCommentsForAll(_config.SSPxConnectionString, protocolVersionKey.ToString()),
                commentsCount = commentCount,
                notes = DBHelper.GetNotes(_config.SSPxConnectionString, pid),
                allUsers = DBHelper.GetAllUsers(_config.SSPxConnectionString),
                standards = DBHelper.GetStandards(_config.SSPxConnectionString),
                dataTypes = AnswerDataType,
                dataUnits = AnswerUnit,
                protocolVersionKey = protocolVersionKey
            };
            return View(protocol);
        }

        [Authorize]
        public IActionResult SSPxProtocol_responsive(String pid = "7")
        {
            // using local DBHelper calls
            GetUserData();

            bool hasEditPermission = _protocolPermissions.HasPermission(Convert.ToInt32(_userKey), Convert.ToInt32(pid), ProtocolPermissionTypes.EditProtocol);
            if (hasEditPermission == false)
            {
                return RedirectToPage("/Index", new { area = "Dashboard" });
            }
            Int32 protocolVersionKey = DBHelper.GetProtocolVersion(_config.SSPxConnectionString, pid);
            ChecklistNoteViewModel protocol = new ChecklistNoteViewModel
            {
                protocolCkey = pid,
                comments = DBHelper.GetProtocolVersionComments(_config.SSPxConnectionString, protocolVersionKey.ToString(), "1_F"),
                notes = DBHelper.GetNotes(_config.SSPxConnectionString, pid),
                allUsers = DBHelper.GetAllUsers(_config.SSPxConnectionString),
                standards = DBHelper.GetStandards(_config.SSPxConnectionString),
                dataTypes = AnswerDataType,
                dataUnits = AnswerUnit,
                protocolVersionKey = protocolVersionKey
            };
            return View(protocol);
        }

        [Authorize]
        public IActionResult SSPxCompareVersions(String pid)
        {
            return View();
        }

        [Authorize]
        public IActionResult SSPxImportItems(String pid)
        {
            return View();
        }

        //public JsonResult SSPxItem(String id)
        //{
        //    ChecklistItem item = DBHelper.GetChecklistItem(_config.SSPxConnectionString, id);
        //    item.notes = DBHelper.GetNoteKeys(_config.SSPxConnectionString, id);
        //    return Json(item);
        //}

        //Zira Id SSP-99
        /// <summary>
        /// Get Case Summary child and sub child items
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public JsonResult SSPxItem(String id, String pid)
        {
            ChecklistItem item = new ChecklistItem();
            List<ChecklistItem> items = new List<ChecklistItem>();
            string treeViewData = "";
            if (id.IndexOf("_C") > 1)
            {
                var versions = DBHelper.GetCheckVersion(_config.SSPxConnectionString, id);
                treeViewData = Treeview(id, "", 0, 0, 0);
                item.Items = JsonConvert.DeserializeObject<List<ChecklistItem>>(treeViewData);
                item.notes = notes;
                item.protocolName = versions[0].protocolName;

            }
            else if (id.IndexOf("_I") > 1)
            {
                item.Items = DBHelper.GetAllNodes(_config.SSPxConnectionString, id);
                item.notes = DBHelper.GetNoteKeys(_config.SSPxConnectionString, id);
            }

sspx.web/Controllers/ProtocolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using sspx.core;
using sspx.core.entities;
using sspx.core.interfaces;

namespace sspx.web.Controllers
{
    public class ProtocolController : Controller
    {
        private readonly IRepository<Protocol> _protocolRepository;

        public ProtocolController(IRepository<Protocol> protocolRepository)
        {
            _protocolRepository = protocolRepository;
        }

        public IActionResult Index()
        {
            var protocols = _protocolRepository.List();
            return View(protocols);
        }

        public IActionResult Load()
        {
            int recordsAdded = DatabasePopulator.LoadProtocols(_protocolRepository);
            return Ok(recordsAdded);
        }

        public IActionResult Edit()
        {
            var protocols = _protocolRepository.List();
            return View(protocols);
        }
    }
}

sspx.web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using sspx.core;
using sspx.core.entities;
using sspx.core.interfaces;

namespace sspx.web.Controllers
{
    public class UserController : Controller
    {
        private readonly IRepository<User> _userRepository;

        public UserController(IRepository<User> userRepository)
        {
            _userRepository = userRepository;
        }

        public IActionResult Index()
        {
            var users = _userRepository.List();
            return View(users);
        }

        public IActionResult Load()
        {
            int recordsAdded = DatabasePopulator.LoadUsers(_userRepository);
            return Ok(recordsAdded);
        }
    }
}

sspx.web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "SSPx";
}

@model IEnumerable<sspx.core.entities.Protocol>
@{
    //Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>Protocols</title>
    <style>
        .details {
            margin: 20px auto;
            width: 35%;
        }

            .details .menu {
                width: 400px;
                padding: 10px;
                border: 1px solid #ccc;
                cursor: pointer;
                margin-bottom: 10px;
                text-align: center;
                margin-right: 10px;
                font-weight: bold;
                font-size: 14px;
                display: block;
                color: #6495ED;
            }

            .details a {
                text-decoration: none;
            }

            .details .menu:hover {
                background-color: #ccc;
                color: #ffffff;
            }
    </style>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <div class="details">
        @{
            //foreach (var protocol in Model)
            //{
            //    <a href="/@protocol.ProtocolId">
            //        <div class="menu">@protocol.ProtocolName</div>
            //    </a>
            //}
        }
    </div>
</body>
</html>

sspx.web/Views/Home/SSPxBuildPdf.cshtml
@model String
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Protocol</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <partial name="_KendoStylesScripts" />
    <!-- Load Pako ZLIB library to enable PDF compression -->
    <script src="https://kendo.cdn.telerik.com/2017.3.913/js/pako_deflate.min.js"></script>
    @* CS2. exclude site UI overrides so they don't affect PDF styling. <partial name="_StyleOverridesLinkLast" />*@
</head>
<body>
    <div>
        <span id="alertMessage" role="alert" style="font-family:Arial;font-size:16px;">
            Generating PDF...
        </span>
    </div>
    <div style="height:1px;overflow:hidden" id="PreviewProtocol">
        <div id="Preview"></div>
    </div>
    <script>
        function getProtocolHtml(protocolKey,pdf) {
            
            var url = '../../OutputHtml/' + protocolKey + '_P?view=full/'+pdf;

            return $.ajax({
                type: "GET",
                url: url,
                cache: false,
                dataType: "html",
                success: function (result) {
                    
                    $('#alertMessage').hide();
                    document.getElementById("PreviewProtocol").style.overflow = "visible";
                    //$('#PreviewProtocol').show();
                    //$('#Preview').html("<div style=\"width: 8.5in\">" + result + "</div>");
                  
                    $('#Preview').html(result);     
                },
                error: function (xhr, status, err) {
                    console.error(url, status, err.toString());
                }
            });
        }

        function drawPDF(data, textStatus, jqXHR) {

            // Convert the DOM element to a drawing using kendo.drawing.drawDOM
            return kendo.drawing.drawDOM($("#Preview"))
                .then(function (group) {
                    // Render the result as a PDF file
                    return kendo.drawing.exportPDF(group, {
                        //paperSize: "Letter",
                        margin: { left: "1cm", top: "1cm", right: "1cm", bottom: "1cm" }
                        // scale: 0.8
                    });
                });
        }

        function openPDF(data, textStatus, jqXHR) {

            // Save the PDF file
            return kendo.saveAs({
                dataURI: data,
                // fileName: "Protocol.pdf", // must omit fileName parameter to show in browser rather than download
                proxyURL: "../../OutputPdf/Protocol.pdf",
                forceProxy: true
            });
        }

        $(document).ready(function () {
            
            getProtocolHtml(@Model,"")
                .then(drawPDF)
                .then(openPDF);
        });
    </script>
</body>
</html>

sspx.web/Views/Home/SSPxCompareVersions.cshtml
@{
    Layout = "_ProtocolLayout";
    ViewData["Title"] = "Compare Versions";
}
@section leftSection {
    <h2>@ViewData["Title"]</h2>
    <hr />
    <h5>TBD</h5>
}

sspx.web/Views/Home/SSPxImportItems.cshtml
@{
    Layout = "_ProtocolLayout";
    ViewData["Title"] = "Import Items";
}
@section leftSection {
    <h2>@ViewData["Title"]</h2>
    <hr />
    <h5>OUT OF SCOPE, > MVP</h5>
}

sspx.web/Views/Home/SSPxProtocolPreview.cshtml
@using sspx.core.entities
@using sspx.web.Models
@using sspx.web.Services
@using Microsoft.Extensions.Options
@inject IOptionsMonitor<PreviewOptions> PreviewOptionsAccessor
@model ChecklistPreviewViewModel
@{
    var nid = Model.nodeCkey;
    var view = Model.view;
    Layout = null;
    var baseUrl = "";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>SSPx Protocol Preview</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <style>

        body {
            font-family: Arial;
            font-size: 12px;
            margin: 20px;
            line-height: 22px;
        }

        #Preview .itemType4, #Preview .itemType17, #Preview .itemType23, #Preview .itemType24 {
            font-weight: 600;
            margin-top: 13px;
        }

        #Preview .itemType24 {
            border-bottom: 1px solid #000000;
            font-size: 14px;
            margin-top: 18px;
        }

        #Preview .highlight {
            background-color: #A3C2A3;
            font-style: italic;
        }

        #Preview .title, #Preview .section, #Preview .subtitle {
            font-weight: bold;
            margin-bottom: 10px;
        }

        #Preview .section {
            font-size: 16px;
            margin-top: 20px;
        }
    </style>
    <script>
        var currentNode = '';
        function hightlightNode(nodeId) {
            if (nodeId.substr(0, 3) !== 'EN-') {
                nodeId = nodeId.replace(/[_I.]/g, '');
            }
            if (currentNode != nodeId) {
                if (currentNode != '') { $('#' + currentNode).removeClass('highlight'); }
                var node = $('#' + nodeId);
                if (node.length > 0) {
                    var parentHeight = $(window).height() - 30;
                    node.addClass('highlight');
                    var scrollto = node.offset().top - (parentHeight / 2);
                    $('html, body').animate({ scrollTop: scrollto }, 'slow');
                    currentNode = nodeId;
                }
            }
        }
    </script>
</head>
<body id="Preview">
    <div style="text-align-last: right">
        @{
            if (ViewBag.ProtocolView == "pdf")
            {
                <a asp-route="SSPxBuildPdf" asp-route-pid="@ViewBag.ProtocolId" class="small"> <span>PDF Download</span></a>

            }
            else if (ViewBag.ProtocolView == "word")
            {
                <a asp-route="SSPxBuildMSWord" asp-route-pid="@ViewBag.ProtocolId" class="small"> <span>Word Download</span></a>
            }
        }
    </div>
    @{
        if (Model.version != null)
        {
            <div class="title" id="1F">@Html.Raw(Model.version.title)</div>
            <div class="cover" id="2F">@Html.Raw(Model.version.cover)</div>
            <div class="section" id="3F">Authors</div>
            foreach (var user in Model.version.users)
            {
                var name = String.Format("{0} {1}. {2}, {3}{4}; ", user.firstName, user.middleName, user.lastName, user.qualification,
                     user.role.Equals("author", StringComparison.OrdinalIgnoreCase) ? PreviewOptionsAccessor.CurrentValue.SSPX_AUTHORS_PRIMARY_SYMBOL : String.Empty);
                @Html.Raw(name)
            }
            <p></p>
            @Html.Raw(PreviewOptionsAccessor.CurrentValue.SSPX_AUTHORS_FOOTER)
        }
        String ConvertToPreviewHtml(ChecklistItemNode nodeData, Boolean parentRequired)
        {
            if (nodeData.hidden)
            {
                return String.Empty;
            }
            var itemType = nodeData.itemType;
            var iClass = "itemType" + itemType.ToString();
            var prefix = String.Empty;
            var suffix = String.Empty;
            if (itemType == 6 || itemType == 20)
            {
                prefix = "___ ";
            }
            if (!nodeData.required && (itemType == 4 || itemType == 17 || itemType == 23))
            {
                prefix = "+ " + prefix;
            }
            if (!parentRequired && (itemType == 6 || itemType == 20))
            {
                prefix = "+ " + prefix;
            }
            if (itemType == 17 || itemType == 20)
            {
                suffix = ": _________________";
            }
            var text = nodeData.titleHtml;
            if (text.Contains("Additional dimensions (repeat section if more than one part)", StringComparison.OrdinalIgnoreCase))
            {
                return String.Empty;
            }
            if (text.ToLower().Equals("not specified") || text.Equals("Cannot be determined")
                || text.Contains("not identified", StringComparison.OrdinalIgnoreCase)
                || text.Contains("not applicable", StringComparison.OrdinalIgnoreCase)
                || text.Contains("indeterminate", StringComparison.OrdinalIgnoreCase))
            {
                suffix = String.Empty;
            }
            if (text.StartsWith("?"))
            {
                text = text.Replace("?", String.Empty);
            }
            if (text.Contains("additional dimension", StringComparison.OrdinalIgnoreCase))
            {
                suffix = ": ____ x ____";
            }
            var id = nodeData.id.Replace(".", "");
            var condition = String.Empty;
            if (!String.IsNullOrWhiteSpace(nodeData.condition))
            {
                condition = $"<br/><i>({nodeData.condition})</i> ";
            }
            var html = $"<div class='{iClass}' id='{id}'>{prefix}{text}{condition}{suffix}</div>";
            var children = Model.items.FindAll(i => i.parentId == nodeData.id);
            if (children.Count > 0)
            {
                for (var i = 0; i < children.Count; i++)
                {
                    html += ConvertToPreviewHtml(children[i], nodeData.required);
                }
            }
            return html;
        }

        var topNodes = Model.items.FindAll(i => i.parentId == "0");
        foreach (var node in topNodes)
        {
            var nodeHtml = ConvertToPreviewHtml(node, false);
            @Html.Raw(nodeHtml);
        }

        if (view == "full")
        {
            if (Model.notes.Count > 0)
            {
                @Html.Raw("<div class='section' id='5F'>Explanatory Notes</div>")
                foreach (var note in Model.notes)
                {
                    <div class='subtitle' id="EN-@note.number">@note.number. @Html.Raw(note.title)</div>
                    @Html.Raw(note.details)
                    if (Model.references.Count > 0)
                    {
                        <div class='section' id='6F'>References</div>
                        <ol>
                            @foreach (var reference in Model.references.Where(i => i.key == Convert.ToInt32(note.key)))
                            {
                                <li>@Html.Raw(reference.reference)</li>
                            }
                        </ol>
                    }
                }
            }
            @*if (Model.references.Count > 0)
                {
                    <div class='section' id='6F'>References</div>
                    <ol>
                        @foreach (var reference in Model.references)
                        {
                            <li>@Html.Raw(reference.reference)</li>
                        }
                    </ol>
                }*@
        }
    }
    <script>
        $(document).ready(function () {
            hightlightNode('@nid');
        });
    </script>
</body>
</html>

sspx.web/Views/Home/SSPxProtocolReader.cshtml
@model sspx.web.Models.ChecklistNoteViewModel
@{
    Layout = "~/Views/Shared/_ProtocolLayout.cshtml";
    var pid = Model.protocolCkey + "_C";
    var nid = Model.nodeCkey.Replace(".", String.Empty).Replace("_I", String.Empty);
}
@section topScripts {
    <style>
        #protocolNodes .k-state-selected {
            background-color: #A3C2A3;
        }

        #Preview {
            display: block;
            border: 1px solid #000000;
            border-right: none;
        }
    </style>
}
@section topSection {
    <div class="topmenu active">Content</div>
}

@section leftSection {
    <div class="sectionHeader">Table of Content</div>
    <div id="protocolNodes"></div>
}

@section midSection {
    <div class="sectionHeader">Preview</div>
    <div id="Preview" class="panel">
        <iframe id="FullPreview" style="width:100%; height:100%; border: 0"></iframe>
    </div>
}

@section rightSection {
    <div id="commentMenu" class="sectionHeader">Comments <span class="badge">@Model.comments.Count</span></div>
    <div class="panelSection">
        @Html.Partial("_Comments", Model)
    </div>
}

@section bottomContent {
    <style>
        #protocolNodes .k-item .k-in {
            width: 93%;
            white-space: normal;
            padding: 3px !important;
        }
    </style>
    <script id="node-template" type="text/kendo-ui-template">
        <span class='#= getIconClass(true, item.itemType) #'></span>
        #= item.titleHtml #
        # if (item.noteNumber && item.noteNumber.length > 0) { # :
        # for (var i = 0; i < item.noteNumber.length; i++) { #
        <a href="javascript:goToNote('EN-#= item.noteNumber[i] #')">#= item.noteNumber[i] #</a>
        # } #
        # } #
        # if (item.commentCount > 0) { #
        <span class='badge'>#= item.commentCount #</span>
        # } #
    </script>
    <script src="~/js/sspx/SSPxProtocol.js"></script>
    <script type="text/javascript">
        var currentVersion = '';
        var currentNode = '';
        var firstLoad = true;
        var protocolCKey = '@Model.protocolCkey';
        var protocol = new kendo.data.HierarchicalDataSource({
            transport: {
                read: {
                    url: "../SSPxItem/@pid/children?view=full",
                    dataType: "json"
                }
            },
            schema: {
                model: {
                    id: "id",
                    hasChildren: "hasItems"
                }
            }
        });

        function getNode(e) {
            var item = this.dataItem(e.node);
            if (item.id.indexOf("_I") > 1) {
                currentNode = item.id;
                document.getElementById("FullPreview").contentWindow.hightlightNode(currentNode);
                $('#Comment .addMeta').show();
            } else if (item.id.indexOf("_F") > 0) {
                currentNode = item.id;
                document.getElementById("FullPreview").contentWindow.hightlightNode(currentNode);
                $('#Comment .addMeta').show();
            }
            commentObject.setCurrentNode(currentNode);
            commentObject.refreshComment();
        }

        function goToNote(noteNo) {
            document.getElementById("FullPreview").contentWindow.hightlightNode(noteNo);
        }

        $(document).ready(function () {
            $("#protocolNodes").kendoTreeView({
                template: kendo.template($("#node-template").html()),
                dataSource: protocol,
                select: getNode,
                dataBound: function (e) {
                    if (firstLoad) {
                        $('#col2 #Preview #FullPreview').attr('src', '../SSPxProtocolPreview/' + protocolCKey + '_P?view=full');
                        firstLoad = false;
                    }
                }
            });
        });

        function setMetaSaveActive() {
            $('#EditMetaData #EditButton').removeAttr('disabled');
        }
    </script>
}

sspx.web/Views/Home/Spike.cshtml
@{
    ViewData["Title"] = "SSPx Architecture Spike";
}

@{
    Layout = null;
}

<div class="row">
    <div class="col-md-6">
        <h1>SSPx Architecture Spike - Release Block #1 (2018.06.29)</h1>
        <h2>API Definitions</h2>
        <ul>
            <li><a href="/swagger">API Documentation</a></li>
        </ul>
        <h2>Users (MVC)</h2>
        <ul>
            <li><a asp-area="" asp-controller="User" asp-action="Load">Load Users</a></li>
            <li><a asp-area="" asp-controller="User" asp-action="Index">List Users</a></li>
        </ul>
        <h2>Users (Razor Pages)</h2>
        <ul>
            <li><a asp-page="/Users/UsersLoad">Load Users</a></li>
            <li><a asp-page="/Users/UsersList">List Users</a></li>
        </ul>
        <h2>Protocols (MVC)</h2>
        <ul>
            <li><a asp-area="" asp-controller="Protocol" asp-action="Load">Load Protocols</a></li>
            <li><a asp-area="" asp-controller="Protocol" asp-action="Index">List Protocols</a></li>
        </ul>
        <h2>Protocols (Razor Pages)</h2>
        <ul>
            <li><a asp-page="/Protocols/ProtocolsLoad">Load Protocols</a></li>
            <li><a asp-page="/Protocols/ProtocolsList">List Protocols</a></li>
        </ul>
    </div>
    <div class="col-md-6">
        <h2>About SSPx</h2>
        <ul>
            <li>GitHub coming soon.</li>
        </ul>
        <h2>About SSP</h2>
        <ul>
            <li><a href="https://github.com/vparekh/SSP">GitHub</a></li>
        </ul>
    </div>
</div>