sspx.web/Areas/Admin/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace sspx.Areas.Admin.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

sspx.web/Areas/Admin/Pages/Protocol.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using sspx.Areas.Admin.data;
using sspx.core.entities;
using sspx.core.interfaces;
using sspx.web.Helpers;
using sspx.web.Services;

namespace sspx.Areas.Admin.Pages
{
    public class ProtocolPageModel : PageModel
    {
        private IProtocolWithGroupRepository _protocolWithGroupRepository;
        private IProtocolGroupRepository _protocolGroupRepository;
        private IProtocolVersionRepository _protocolVersionRepository;

        public string Title { get; set; } = "Create Protocol";
        public SearchModel ProtocolsWithGroupsSearchModel { get; set; }

        [BindProperty]
        public int ProtocolKey { get; set; } = DefaultValue.Key;
        [BindProperty]
        public int ProtocolVersionKey { get; set; } = DefaultValue.Key;
        [BindProperty]
        public bool TestProtocol { get; set; } = false;

        public bool EditMode { get; set; } = false;

        #region User Inputs

        [BindProperty]
        [Display(Name = "Protocol Group")]
        [Range(1, int.MaxValue, ErrorMessage = "Protocol Group is required")]
        public int ProtocolGroupKey { get; set; }

        [Required(ErrorMessage = "Name is required")]
        [BindProperty]
        [DataType(DataType.Text)]
        [Display (Name = "Protocol Name")]
        public string ProtocolName { get; set; }

        [Required(ErrorMessage = "Protocol Short Name is required")]
        [BindProperty]
        [DataType(DataType.Text)]
        [Display(Name = "Protocol Short Name")]
        public string ProtocolShortName { get; set; }

        [Required(ErrorMessage = "Protocol Version is required")]
        [BindProperty]
        [DataType(DataType.Text)]
        [Display(Name = "Protocol Version")]
        public string ProtocolVersion { get; set; }

        // CS2. DataType.Text (not Date) seems to avoid error with not persisting after validation fail https://stackoverflow.com/a/52188352/7803135
        [BindProperty]
        [DataType(DataType.Text)] 
        [Display(Name = "Publish Date")]
        public DateTime? PublishDate { get; set; } = null;

        [BindProperty]
        [Display(Name = "Status")]
        public bool Active { get; set; } = DefaultValue.Active;

        #endregion

        [BindProperty]
        public List<ProtocolGroup> ProtocolGroupsForDropDown { get; set; }

        [TempData]
        public string StatusMessage { get; set; }

        public ProtocolPageModel(IProtocolWithGroupRepository protocolWithGroupRepository, IProtocolGroupRepository protocolGroupRepository, IProtocolVersionRepository protocolVersionRepository)
        {
            _protocolWithGroupRepository = protocolWithGroupRepository;
            _protocolGroupRepository = protocolGroupRepository;
            _protocolVersionRepository = protocolVersionRepository;
        }

        public IActionResult OnGet(int protocolKey)
        {
            SetUpPage(protocolKey);

            var protocolsWithGroups = _protocolWithGroupRepository.List();
            var pageUrl = Url.Page("Protocol", new { protocolKey = "" });
            ProtocolsWithGroupsSearchModel = SearchModel.FromProtocolsWithGroups(pageUrl, protocolsWithGroups);
            HttpContext.Session.Set("protocolsWithGroupsSearchModel", ProtocolsWithGroupsSearchModel);

            if (protocolKey > 0)
            {
                var protocolWithGroup = _protocolWithGroupRepository.GetByKey(protocolKey);

                // TODO CS2:
                var protocolVersion = _protocolVersionRepository.GetLatestVersionForProtocolIncludingInactive(protocolKey);
                var missingProtocolOrVersion = (protocolWithGroup == null || protocolVersion == null);
                if (missingProtocolOrVersion)
                {
                    // TODO CS2:
                    return RedirectToPage("Protocol", new { protocolKey = "" });
                }

                ProtocolGroupKey = protocolWithGroup.ProtocolGroupKey;
                ProtocolKey = protocolWithGroup.ProtocolKey;
                ProtocolName = protocolWithGroup.ProtocolName;
                ProtocolShortName = protocolWithGroup.ProtocolShortName;
                TestProtocol = protocolWithGroup.TestProtocol;
                Active = protocolWithGroup.ProtocolActive;

                ProtocolVersionKey = protocolVersion.ProtocolVersionKey;
                ProtocolVersion = protocolVersion.ProtocolVersionText;
                PublishDate = protocolVersion.ReleaseDate;
            }

            return Page();
        }

        public IActionResult OnPostSave([FromServices] IHostingEnvironment hostingEnvironment)
        {
            SetUpPage(this.ProtocolKey);
            if (ModelState.IsValid == false)
            {
                return Page();
            }

            var userKey = HttpContext.Session.Get<int>("userKey");

            // TODO CS2:

            var protocolWithGroup = new ProtocolWithGroup()
            {
                ProtocolGroupKey = this.ProtocolGroupKey,
                ProtocolName = this.ProtocolName,
                ProtocolShortName = this.ProtocolShortName,
                ProtocolSortName = this.ProtocolName, // default to name
                ProtocolActive = this.Active,
                LastUpdated = userKey
            };

            bool isNewProtocol = (this.ProtocolKey == DefaultValue.Key);
            if (isNewProtocol == true)
            {
                var createdInDevelopmentEnvironment = hostingEnvironment.IsDevelopment();

                protocolWithGroup.CreatedBy = userKey;
                protocolWithGroup.TestProtocol = createdInDevelopmentEnvironment;

                var newProtocolWithGroup = _protocolWithGroupRepository.Add(protocolWithGroup);
                if (newProtocolWithGroup == null)
                {
                    ModelState.AddModelError(string.Empty, "Failed to create protocol");
                    StatusMessage = string.Empty;
                    return Page();
                }

                ProtocolKey = newProtocolWithGroup.ProtocolKey;

                var protocolVersion = new ProtocolVersion()
                {
                    ProtocolKey = ProtocolKey,
                    ProtocolVersionText = this.ProtocolVersion,
                    TestVersion = createdInDevelopmentEnvironment,
                    Title = this.ProtocolName, // defaulting to Protocol Name
                    SubTitle = string.Empty,
                    ReleaseDate = this.PublishDate,
                    WebPostingDate = this.PublishDate, // defaulting to Publish Date
                    UserKey = userKey,
                    LastUpdated = userKey,
                    Active = true
                };

                var newProtocolVersion = _protocolVersionRepository.Add(protocolVersion);
                if (newProtocolVersion == null)
                {
                    ModelState.AddModelError(string.Empty, "Failed to create protocol version");
                    StatusMessage = string.Empty;
                    return Page();
                }

                ProtocolVersionKey = newProtocolVersion.ProtocolVersionKey;
                StatusMessage = "Protocol created successfully";
            }
            else
            {
                protocolWithGroup.ProtocolKey = this.ProtocolKey;
                protocolWithGroup.LastUpdated = userKey;
                protocolWithGroup.TestProtocol = this.TestProtocol;

                string error = _protocolWithGroupRepository.Update(protocolWithGroup);
                if (error != string.Empty)
                {
                    ModelState.AddModelError(string.Empty, "Could not save protocol");
                    StatusMessage = string.Empty;
                    return Page();
                }

                var protocolVersionToUpdate = _protocolVersionRepository.GetByKey(ProtocolVersionKey);
                protocolVersionToUpdate.ProtocolVersionText = this.ProtocolVersion;
                protocolVersionToUpdate.Title = this.ProtocolName;
                protocolVersionToUpdate.ReleaseDate = this.PublishDate;
                protocolVersionToUpdate.LastUpdated = userKey;

                error = _protocolVersionRepository.Update(protocolVersionToUpdate);
                if (error != string.Empty)
                {
                    ModelState.AddModelError(string.Empty, "Could not update protocol version");
                    StatusMessage = string.Empty;
                    return Page();
                }

                StatusMessage = "Protocol saved successfully";
            }

            return RedirectToPage("ProtocolCaseSummary", new { protocolVersionKey = this.ProtocolVersionKey });
        }

        // TODO CS2:

        private void SetUpPage(int protocolKey)
        {
            ProtocolGroupsForDropDown = _protocolGroupRepository.ListActive();

            if(protocolKey > 0)
            {
                EditMode = true;
                Title = $"Edit Protocol - {ProtocolName}";
            }
        }
    }
}

sspx.web/Areas/Admin/Pages/ProtocolGroup.cshtml.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using sspx.Areas.Admin.data;
using sspx.core.entities;
using sspx.web.Helpers;
using sspx.web.Services;

namespace sspx.Areas.Admin.Pages
{
    public class ProtocolGroupPageModel : PageModel
    {
        private IProtocolGroupRepository _protocolGroupRepository;

        public SearchModel ProtocolGroupSearchModel { get; set; }

        [BindProperty]
        public int ProtocolGroupKey { get; set; } = DefaultValue.Key;

        public bool EditMode { get; set; } = false;

        [Required(ErrorMessage = "Group is required")]
        [BindProperty]
        [DataType(DataType.Text)]
        [Display(Name = "Group Name")]
        public string ProtocolGroupName { get; set; }

        [BindProperty]
        [Display(Name = "Status")]
        public bool Active { get; set; } = DefaultValue.Active;

        [TempData]
        public string ErrorMessage { get; set; }
        [TempData]
        public string StatusMessage { get; set; }

        public ProtocolGroupPageModel([FromServices] IProtocolGroupRepository protocolGroupRepository)
        {
            _protocolGroupRepository = protocolGroupRepository;
        }

        public IActionResult OnGet(int protocolGroupKey)
        {
            var protocolGroups = _protocolGroupRepository.List();
            var pageUrl = Url.Page("ProtocolGroup", new { protocolGroupKey = "" });

            ProtocolGroupSearchModel = SearchModel.FromProtocolGroups(pageUrl, protocolGroups);
            HttpContext.Session.Set("protocolGroupSearchModel", ProtocolGroupSearchModel);

            if (protocolGroupKey > 0)
            {
                ProtocolGroup protocolGroup = _protocolGroupRepository.GetByKey(protocolGroupKey);
                if (protocolGroup == null)
                {
                    return RedirectToPage("ProtocolGroup", new { protocolGroupKey = "" });
                }

                protocolGroupKey = protocolGroup.ProtocolGroupKey;
                ProtocolGroupName = protocolGroup.ProtocolGroupName;
                Active = protocolGroup.Active;

                ViewData["Title"] = string.Format("Edit Protocol Group - {0}", ProtocolGroupName);
                EditMode = true;
            }
            else
            {
                ViewData["Title"] = "Create Protocol Group";
            }
            
            return Page();
        }

        public IActionResult OnPostSave()
        {
            if (ModelState.IsValid == false)
            {
                return Page();
            }

            var userKey = HttpContext.Session.Get<int>("userKey");
            ProtocolGroup protocolGroup = new ProtocolGroup()
            {
                ProtocolGroupName = this.ProtocolGroupName,
                ProtocolGroupSortName = this.ProtocolGroupName, // since we don't have a sort field in UI, just use the Group Name
                Active = this.Active
            };

            var protocolGroupKey = this.ProtocolGroupKey;
            bool isNewProtocolGroup = (protocolGroupKey == DefaultValue.Key);

            if (isNewProtocolGroup == true)
            {
                protocolGroup.CreatedBy = userKey;
                protocolGroup.LastUpdated = userKey;

                var newProtocolGroup = _protocolGroupRepository.Add(protocolGroup);
                if (newProtocolGroup == null)
                {
                    ErrorMessage = "Failed to create Protocol Group";
                    StatusMessage = string.Empty;
                    return Page();
                }
                protocolGroupKey = newProtocolGroup.ProtocolGroupKey;
                ErrorMessage = string.Empty;
                StatusMessage = "Protocol Group created successfully";
            }
            else
            {
                protocolGroup.ProtocolGroupKey = protocolGroupKey;
                protocolGroup.LastUpdated = userKey;

                string error = _protocolGroupRepository.Update(protocolGroup);
                if (error != string.Empty)
                {
                    ErrorMessage = "Could not save protocolGroup";
                    StatusMessage = string.Empty;
                    return Page();
                }

                ErrorMessage = string.Empty;
                StatusMessage = "Protocol Group saved successfully";
            }

            return RedirectToPage("ProtocolGroup", new { protocolGroupKey = protocolGroupKey });
        }

        public IActionResult OnPostDelete()
        {
            var userKey = HttpContext.Session.Get<int>("userKey");
            var protocolGroup = new ProtocolGroup()
            {
                ProtocolGroupKey = this.ProtocolGroupKey,
                LastUpdated = userKey
            };

            string error = _protocolGroupRepository.Delete(protocolGroup);
            if (error != string.Empty)
            {
                ErrorMessage = "Could not remove Protocol Group";
                StatusMessage = string.Empty;
                return Page();
            }

            ErrorMessage = string.Empty;
            StatusMessage = "Protocol Group has been deactivated";

            return RedirectToPage("ProtocolGroup", new { ProtocolGroupKey = "" });
        }
    }
}

sspx.web/Areas/Protocols/Pages/AllProtocols.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace sspx.web.Areas.Protocols.Pages
{
    public class AllProtocolsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

sspx.web/Areas/Protocols/Pages/MyProtocols.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using sspx.web.Helpers;
using sspx.web.Models;
using sspx.web.Services;

namespace sspx.web.Areas.Protocols.Pages
{
    public class MyProtocolsModel : PageModel
    {
        public int UserKey { get; private set; }

        private IProtocolIndexData _protocolIndexData;

        [BindProperty]
        public ProtocolIndexModel ProtocolIndex { get; set; }

        public MyProtocolsModel(IProtocolIndexData protocolIndexData)
        {
            _protocolIndexData = protocolIndexData;
        }

        public void OnGet()
        {
            UserKey = HttpContext.Session.Get<int>("userKey");
            ProtocolIndex = _protocolIndexData.GetForUser(UserKey);
        }
    }
}

sspx.web/Controllers/ProtocolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using sspx.core;
using sspx.core.entities;
using sspx.core.interfaces;

namespace sspx.web.Controllers
{
    public class ProtocolController : Controller
    {
        private readonly IRepository<Protocol> _protocolRepository;

        public ProtocolController(IRepository<Protocol> protocolRepository)
        {
            _protocolRepository = protocolRepository;
        }

        public IActionResult Index()
        {
            var protocols = _protocolRepository.List();
            return View(protocols);
        }

        public IActionResult Load()
        {
            int recordsAdded = DatabasePopulator.LoadProtocols(_protocolRepository);
            return Ok(recordsAdded);
        }

        public IActionResult Edit()
        {
            var protocols = _protocolRepository.List();
            return View(protocols);
        }
    }
}

sspx.web/Pages/Protocols/ProtocolsList.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using sspx.core.entities;
using sspx.core.interfaces;

namespace sspx.web.Pages.Protocols
{
    public class IndexModel : PageModel
    {
        private readonly IRepository<Protocol> _protocolRepository;

        public List<Protocol> Protocols { get; set; }

        public IndexModel(IRepository<Protocol> protocolRepository)
        {
            _protocolRepository = protocolRepository;
        }

        public void OnGet()
        {
            Protocols = _protocolRepository.List();
        }
    }
}

sspx.web/Areas/Admin/Pages/Index.cshtml
@page
@model sspx.Areas.Admin.Pages.IndexModel
@{
    ViewData["Title"] = "Admin Home (placeholder page)";
}

@section mainSection {
    <h2>@ViewData["Title"]</h2>
}

sspx.web/Areas/Admin/Pages/ProtocolGroup.cshtml
@page "{protocolGroupKey:int?}"
@namespace sspx.Areas.Admin.Pages
@model ProtocolGroupPageModel
@using sspx.Areas.Admin.data
@using sspx.core.entities
@using sspx.infra.data;
@using sspx.web.Helpers;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    var pageLoadingWithoutModel = (Model.ProtocolGroupSearchModel == null);
    if (pageLoadingWithoutModel == true)
    {
        var searchModelBackup = HttpContext.Session.Get<SearchModel>("protocolGroupSearchModel");
        if (searchModelBackup != null)
        {
            Model.ProtocolGroupSearchModel = searchModelBackup;
        }
    }
}

@section leftSection {
    <partial name="_Search" for="ProtocolGroupSearchModel" />
}

@section mainSection {
    <div class="row">
        <div class="col-sm-8">
            <h5>@ViewData["Title"]</h5>
        </div>
        @if (Model.EditMode == true)
        {
            <div class="col-sm-4">
                <i class="fas fa-times fa-lg text-danger align-middle mr-2"></i>
                <small><a href="#" class="text-danger" data-toggle="modal" data-target="#removeModal">Remove this Protocol Group</a></small>
            </div>
        }
    </div>

    @if (string.IsNullOrWhiteSpace(@Model.ErrorMessage) == false)
    {
        <p class="text-danger">@Model.ErrorMessage</p>
    }
    <div asp-validation-summary="All" class="text-danger"></div>
    @if (string.IsNullOrWhiteSpace(@Model.StatusMessage) == false)
    {
        <p class="text-success">@Model.StatusMessage</p>
    }

    <form method="post">
        <input type="hidden" asp-for="ProtocolGroupKey" />
        <div class="form-row">
            <div class="form-group col">
                <label asp-for="ProtocolGroupName"></label>
                <input asp-for="ProtocolGroupName" />
            </div>
        </div>
        <div class="row">
            <div class="ml-3">
                <label asp-for="Active"></label>
                <input type="checkbox" asp-for="Active" />
                <span id="activeIndicator"></span>
                <!-- TODO: show as button
                            https://getbootstrap.com/docs/4.0/components/buttons/#checkbox-and-radio-buttons
                        <div class="btn-group-toggle" data-toggle="buttons">
                          <label class="btn btn-secondary active">
                            <input type="checkbox" checked autocomplete="off"> Checked
                          </label>
                        </div>

                        <div class="btn-group-toggle" data-toggle="buttons">
                            <label class="btn btn-secondary active">
                                <input type="checkbox" asp-for="Active" />
                            </label>
                        </div>
                -->
            </div>
        </div>
        <div class="row">
            <button type="submit" asp-page-handler="Save" class="btn btn-primary btn-sm ml-3">Save</button>
            @if (Model.EditMode == true)
            {
                <small class="align-self-center ml-4"><a asp-area="Admin" asp-page="ProtocolGroup" asp-route-protocolGroupKey="@DefaultValue.Key">Cancel changes</a></small>
            }
        </div>
    </form>

    <!-- Modal -->
    <div class="modal fade" id="removeModal" tabindex="-1" role="dialog" aria-labelledby="removeModalTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="removeModalLongTitle">Remove Protocol Group</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="text-muted">Group Name</div>
                    <div>@Model.ProtocolGroupName</div>
                    <div class="text-danger">Are you sure you want to remove?</div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
                    <form method="post">
                        <button type="submit" asp-page-handler="Delete">Remove</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
}

sspx.web/Areas/Admin/Pages/Qualification.cshtml
@page "{qualificationKey:int?}"
@namespace sspx.Areas.Admin.Pages
@model QualificationPageModel
@using sspx.Areas.Admin.data
@using sspx.core.entities
@using sspx.infra.data;
@using sspx.web.Helpers;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    var pageLoadingWithoutModel = (Model.QualificationsSearchModel == null);
    if (pageLoadingWithoutModel == true)
    {
        var searchModelBackup = HttpContext.Session.Get<SearchModel>("qualificationSearchModel");
        if (searchModelBackup != null)
        {
            Model.QualificationsSearchModel = searchModelBackup;
        }
    }
}

@section leftSection {
    <partial name="_Search" for="QualificationsSearchModel" />
}

@section mainSection {
    <h5>Create Qualification</h5>
    @if (string.IsNullOrWhiteSpace(@Model.ErrorMessage) == false)
    {
        <p class="text-danger">@Model.ErrorMessage</p>
    }
    <div asp-validation-summary="All" class="text-danger"></div>
    @if (string.IsNullOrWhiteSpace(@Model.StatusMessage) == false)
    {
        <p class="text-success">@Model.StatusMessage</p>
    }

    <form method="post">
        <input type="hidden" asp-for="QualificationKey" />
        <div class="form-row">
            <div class="form-group col">
                <label asp-for="QualificationTxt"></label>
                <input asp-for="QualificationTxt" />
            </div>
            <div class="form-group col">
                <label asp-for="Description"></label>
                <input asp-for="Description" />
            </div>
        </div>
        <div class="row">
            <div class="ml-3">
                <label asp-for="Active"></label>
                <input type="checkbox" asp-for="Active" />
                <span id="activeIndicator"></span>
                <!-- TODO: show as button
                            https://getbootstrap.com/docs/4.0/components/buttons/#checkbox-and-radio-buttons
                        <div class="btn-group-toggle" data-toggle="buttons">
                          <label class="btn btn-secondary active">
                            <input type="checkbox" checked autocomplete="off"> Checked
                          </label>
                        </div>

                        <div class="btn-group-toggle" data-toggle="buttons">
                            <label class="btn btn-secondary active">
                                <input type="checkbox" asp-for="Active" />
                            </label>
                        </div>
                -->
            </div>
        </div>
        <div class="row">
            <button type="submit" asp-page-handler="Save" class="btn btn-primary btn-sm ml-3">Save</button>
            @if (Model.QualificationKey > 0)
            {
                <small class="align-self-center ml-4"><a asp-area="Admin" asp-page="Qualification" asp-route-qualificationKey="@DefaultValue.Key">Cancel changes</a></small>
            }
        </div>
    </form>
}

sspx.web/Areas/Admin/Pages/Standard.cshtml
@page "{standardCkey:decimal?}"
@namespace sspx.Areas.Admin.Pages
@model StandardPageModel
@using sspx.Areas.Admin.data
@using sspx.core.entities
@using sspx.infra.data;
@using sspx.web.Helpers;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    var pageLoadingWithoutModel = (Model.StandardSearchModel == null);
    if (pageLoadingWithoutModel == true)
    {
        var searchModelBackup = HttpContext.Session.Get<SearchModel>("standardSearchModel");
        if(searchModelBackup != null)
        {
            Model.StandardSearchModel = searchModelBackup;
        }
    }
}

@section leftSection {
    <partial name="_Search" for="StandardSearchModel" />
}

@section mainSection {
    <div class="row">
        <div class="col-sm-8">
            <h5>Create Standard@* TODO CS2 @Model.Title*@</h5>
        </div>
        @if (Model.EditMode == true)
        {
            <div class="col-sm-4">
                <i class="fas fa-times fa-lg text-danger align-middle mr-2"></i>
                <small><a href="#" class="text-danger" data-toggle="modal" data-target="#removeModal">Remove this Standard</a></small>
            </div>
        }
    </div>

    @if (string.IsNullOrWhiteSpace(@Model.ErrorMessage) == false)
    {
        <p class="text-danger">@Model.ErrorMessage</p>
    }
    <div asp-validation-summary="All" class="text-danger"></div>
    @if (string.IsNullOrWhiteSpace(@Model.StatusMessage) == false)
    {
        <p class="text-success">@Model.StatusMessage</p>
    }

    <form method="post">
        <input type="hidden" asp-for="StandardCkey" />
        <div class="form-row">
            <div class="form-group col">
                <label asp-for="StandardName"></label>
                <input asp-for="StandardName" />
            </div>
            <div class="form-group col">
                <label asp-for="Description"></label>
                <input asp-for="Description" />
            </div>
        </div>
        <div class="row">
            <div class="ml-3">
                <label asp-for="Active"></label>
                <input type="checkbox" asp-for="Active" />
                <span id="activeIndicator"></span>
                <!-- TODO: show as button
                            https://getbootstrap.com/docs/4.0/components/buttons/#checkbox-and-radio-buttons
                        <div class="btn-group-toggle" data-toggle="buttons">
                          <label class="btn btn-secondary active">
                            <input type="checkbox" checked autocomplete="off"> Checked
                          </label>
                        </div>

                        <div class="btn-group-toggle" data-toggle="buttons">
                            <label class="btn btn-secondary active">
                                <input type="checkbox" asp-for="Active" />
                            </label>
                        </div>
                -->
            </div>
        </div>
        <div class="row">
            <button type="submit" asp-page-handler="Save" class="btn btn-primary btn-sm ml-3">Save</button>
            @if (Model.EditMode == true)
            {
                <small class="align-self-center ml-4"><a asp-area="Admin" asp-page="Standard" asp-route-standardCkey="@DefaultValue.Ckey">Cancel changes</a></small>
            }
        </div>
    </form>

    <!-- Modal -->
    <div class="modal fade" id="removeModal" tabindex="-1" role="dialog" aria-labelledby="removeModalTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="removeModalLongTitle">Remove Standard</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="text-muted">Group Name</div>
                    <div>@Model.StandardName</div>
                    <div class="text-danger">Are you sure you want to remove?</div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
                    <form method="post">
                        <button type="submit" asp-page-handler="Delete">Remove</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
}